# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Table.create!(code: "N1", name: "Bàn 1", table_type: 0, table_location: 1)
Table.create!(code: "N2", name: "Bàn 2", table_type: 0, table_location: 1)
Table.create!(code: "N3", name: "Bàn 3", table_type: 0, table_location: 1)
Table.create!(code: "N4", name: "Bàn 4", table_type: 0, table_location: 1)
Table.create!(code: "N5", name: "Bàn 5", table_type: 0, table_location: 1)
Table.create!(code: "N6", name: "Bàn 6", table_type: 0, table_location: 1)
Table.create!(code: "N7", name: "Bàn 7", table_type: 0, table_location: 1)
Table.create!(code: "N8", name: "Bàn 8", table_type: 0, table_location: 1)
Table.create!(code: "N9", name: "Bàn 9", table_type: 0, table_location: 1)
Table.create!(code: "N10", name: "Bàn 10", table_type: 0, table_location: 1)
Table.create!(code: "N11", name: "Bàn 11", table_type: 0, table_location: 1)
Table.create!(code: "N12", name: "Bàn 12", table_type: 0, table_location: 1)

Table.create!(code: "S1", name: "Bàn 13", table_type: 0, table_location: 2)
Table.create!(code: "S2", name: "Bàn 14", table_type: 0, table_location: 2)
Table.create!(code: "S3", name: "Bàn 15", table_type: 0, table_location: 2)
Table.create!(code: "S4", name: "Bàn 16", table_type: 0, table_location: 2)
Table.create!(code: "S5", name: "Bàn 17", table_type: 0, table_location: 2)
Table.create!(code: "S6", name: "Bàn 18", table_type: 0, table_location: 2)
Table.create!(code: "S7", name: "Bàn 19", table_type: 0, table_location: 2)
Table.create!(code: "S8", name: "Bàn 20", table_type: 0, table_location: 2)

Table.create!(code: "S9", name: "Bàn 21", table_type: 0, table_location: 3)
Table.create!(code: "S10", name: "Bàn 22", table_type: 0, table_location: 3)
Table.create!(code: "S11", name: "Bàn 23", table_type: 0, table_location: 3)
Table.create!(code: "S12", name: "Bàn 24", table_type: 0, table_location: 3)
Table.create!(code: "S13", name: "Bàn 25", table_type: 0, table_location: 3)
Table.create!(code: "S14", name: "Bàn 26", table_type: 0, table_location: 3)

Category.create!(code: "L1", name: "Đồ Uống")
Category.create!(code: "L2", name: "Đồ Pha Chế")
Category.create!(code: "L3", name: "Thuốc")

Product.create!(category_id: 1, code: "CC", name: "Cô Ca", price: 15000)
Product.create!(category_id: 1, code: "PS", name: "Pépsi", price: 12000)
Product.create!(category_id: 1, code: "ST", name: "Sting", price: 12000)
Product.create!(category_id: 1, code: "KN", name: "Khoáng Ngọt", price: 30000)
Product.create!(category_id: 1, code: "KM", name: "Khoáng Mặn", price: 45000)
Product.create!(category_id: 1, code: "KM", name: "Nuti", price: 15000)
Product.create!(category_id: 1, code: "KM", name: "Trà Xanh 0 Độ", price: 12000)

Product.create!(category_id: 2, code: "TS", name: "Trà Sửa", price: 6000)
Product.create!(category_id: 2, code: "TD", name: "Trà Đào", price: 23000)
Product.create!(category_id: 2, code: "TC", name: "Trà Chanh", price: 49000)
Product.create!(category_id: 2, code: "CV", name: "Chivast", price: 28000)
Product.create!(category_id: 2, code: "ND", name: "Nước Dưa Hấu", price: 11000)
Product.create!(category_id: 2, code: "NDT", name: "Nước Dâu Tây", price: 14000)
Product.create!(category_id: 2, code: "SCND", name: "S.Tố Nha Đam", price: 22000)
Product.create!(category_id: 2, code: "SCND", name: "Phê Sữa", price: 12000)
Product.create!(category_id: 2, code: "SCND", name: "Phê Đen", price: 10000)
Product.create!(category_id: 2, code: "SCND", name: "Phê Sữa SG", price: 14000)
Product.create!(category_id: 2, code: "SCND", name: "Phê Đen SG", price: 12000)

Product.create!(category_id: 3, code: "TN", name: "Thuốc Ngựa", price: 1500)
Product.create!(category_id: 3, code: "TS", name: "Thuốc Zed", price: 1500)
Product.create!(category_id: 3, code: "TS", name: "Thuốc DunHill", price: 2000)
Product.create!(category_id: 3, code: "TS", name: "Ba số", price: 1500)
Product.create!(category_id: 3, code: "TS", name: "Sỳ Gà", price: 13000)
