# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Table.create!(code: "N1", name: "Bàn 1", table_type: 0, table_location: 1)
Table.create!(code: "N2", name: "Bàn 2", table_type: 0, table_location: 1)
Table.create!(code: "N3", name: "Bàn 3", table_type: 0, table_location: 1)
Table.create!(code: "N4", name: "Bàn 4", table_type: 0, table_location: 1)
Table.create!(code: "N5", name: "Bàn 5", table_type: 0, table_location: 1)
Table.create!(code: "N6", name: "Bàn 6", table_type: 0, table_location: 1)
Table.create!(code: "N7", name: "Bàn 7", table_type: 0, table_location: 1)
Table.create!(code: "N8", name: "Bàn 8", table_type: 0, table_location: 1)
Table.create!(code: "N9", name: "Bàn 9", table_type: 0, table_location: 1)
Table.create!(code: "N10", name: "Bàn 10", table_type: 0, table_location: 1)
Table.create!(code: "N11", name: "Bàn 11", table_type: 0, table_location: 1)
Table.create!(code: "N12", name: "Bàn 12", table_type: 0, table_location: 1)

Table.create!(code: "S1", name: "Bàn 13", table_type: 0, table_location: 2)
Table.create!(code: "S2", name: "Bàn 14", table_type: 0, table_location: 2)
Table.create!(code: "S3", name: "Bàn 15", table_type: 0, table_location: 2)
Table.create!(code: "S4", name: "Bàn 16", table_type: 0, table_location: 2)
Table.create!(code: "S5", name: "Bàn 17", table_type: 0, table_location: 2)
Table.create!(code: "S6", name: "Bàn 18", table_type: 0, table_location: 2)
Table.create!(code: "S7", name: "Bàn 19", table_type: 0, table_location: 2)
Table.create!(code: "S8", name: "Bàn 20", table_type: 0, table_location: 2)

Table.create!(code: "S9", name: "Bàn 21", table_type: 0, table_location: 3)
Table.create!(code: "S10", name: "Bàn 22", table_type: 0, table_location: 3)
Table.create!(code: "S11", name: "Bàn 23", table_type: 0, table_location: 3)
Table.create!(code: "S12", name: "Bàn 24", table_type: 0, table_location: 3)
Table.create!(code: "S13", name: "Bàn 25", table_type: 0, table_location: 3)
Table.create!(code: "S14", name: "Bàn 26", table_type: 0, table_location: 3)

Category.create!(code: "L1", name: "Đồ Uống")
Category.create!(code: "L2", name: "Đồ Pha Chế")
Category.create!(code: "L3", name: "Thuốc")

Product.create!(category_id: 1, code: "CC", name: "Cô Ca", price: 12000)
Product.create!(category_id: 1, code: "PS", name: "Pépsi", price: 12000)
Product.create!(category_id: 1, code: "ST", name: "Sting", price: 12000)
Product.create!(category_id: 1, code: "ST", name: "Revice", price: 12000)
Product.create!(category_id: 1, code: "ST", name: "7-UP", price: 12000)
Product.create!(category_id: 1, code: "ST", name: "Nước Suối", price: 12000)
Product.create!(category_id: 1, code: "ST", name: "Khoáng Ngọt", price: 12000)
Product.create!(category_id: 1, code: "ST", name: "Nước Bí Đao", price: 12000)
Product.create!(category_id: 1, code: "KM", name: "Khoáng Mặn", price: 12000)
Product.create!(category_id: 1, code: "KM", name: "Nuti", price: 15000)
Product.create!(category_id: 1, code: "KM", name: "Trà Xanh 0 Độ", price: 12000)
Product.create!(category_id: 2, code: "SCND", name: "Nước Me", price: 12000)
Product.create!(category_id: 2, code: "SCND", name: "Bò Húc", price: 15000)

Product.create!(category_id: 2, code: "TS", name: "Hồng Trà", price: 25000)
Product.create!(category_id: 2, code: "TS", name: "Trà Gừng", price: 20000)
Product.create!(category_id: 2, code: "TD", name: "Trà Đào", price: 25000)
Product.create!(category_id: 2, code: "TC", name: "Trà Chanh Lipton", price: 20000)
Product.create!(category_id: 2, code: "CV", name: "Trà Lipton", price: 20000)

Product.create!(category_id: 2, code: "ND", name: "Nước Dưa Hấu", price: 20000)
Product.create!(category_id: 2, code: "NDT", name: "Nước Ổi", price: 18000)
Product.create!(category_id: 2, code: "NDT", name: "Nước Cốc", price: 25000)
Product.create!(category_id: 2, code: "NDT", name: "Nước Cam", price: 25000)
Product.create!(category_id: 2, code: "NDT", name: "Nước Táo", price: 25000)
Product.create!(category_id: 2, code: "NDT", name: "Nước Cà Rốt", price: 20000)
Product.create!(category_id: 2, code: "NDT", name: "Nước Thơm", price: 20000)
Product.create!(category_id: 2, code: "NDT", name: "Nước Bưởi", price: 25000)
Product.create!(category_id: 2, code: "NDT", name: "Nước Cà Chua", price: 20000)
Product.create!(category_id: 2, code: "NDT", name: "Nước Chanh", price: 15000)
Product.create!(category_id: 2, code: "NDT", name: "Nước Chanh Dây", price: 15000)
Product.create!(category_id: 2, code: "NDT", name: "Nước Chanh Mật", price: 20000)
Product.create!(category_id: 2, code: "NDT", name: "Nước Chanh Tuyết", price: 20000)

Product.create!(category_id: 2, code: "SCND", name: "S.Tố Dâu Tây", price: 22000)
Product.create!(category_id: 2, code: "SCND", name: "S.Tố Việt Quất", price: 22000)
Product.create!(category_id: 2, code: "SCND", name: "S.Tố Mâm Xôi", price: 22000)
Product.create!(category_id: 2, code: "SCND", name: "S.Tố Chanh Xây", price: 22000)
Product.create!(category_id: 2, code: "SCND", name: "S.Tố Thơm", price: 22000)
Product.create!(category_id: 2, code: "SCND", name: "S.Tố Nha Đam", price: 22000)
Product.create!(category_id: 2, code: "SCND", name: "S.Tố Xoài", price: 22000)
Product.create!(category_id: 2, code: "SCND", name: "S.Tố Đào", price: 22000)
Product.create!(category_id: 2, code: "SCND", name: "S.Tố Kiwi", price: 22000)
Product.create!(category_id: 2, code: "SCND", name: "S.Tố Bơ", price: 25000)
Product.create!(category_id: 2, code: "SCND", name: "S.Tố Chuối Cookie", price: 25000)

Product.create!(category_id: 2, code: "SCND", name: "Phê Sữa", price: 12000)
Product.create!(category_id: 2, code: "SCND", name: "Phê Đen", price: 10000)
Product.create!(category_id: 2, code: "SCND", name: "Phê Sữa SG", price: 14000)
Product.create!(category_id: 2, code: "SCND", name: "Phê Đen SG", price: 12000)
Product.create!(category_id: 2, code: "SCND", name: "Phê Kiểu Mỹ", price: 20000)
Product.create!(category_id: 2, code: "SCND", name: "Cà Phê Dừa", price: 25000)
Product.create!(category_id: 2, code: "SCND", name: "Cà Phê Soda", price: 20000)
Product.create!(category_id: 2, code: "SCND", name: "Sôcôla", price: 20000)
Product.create!(category_id: 2, code: "SCND", name: "Ca Cao", price: 25000)
Product.create!(category_id: 2, code: "SCND", name: "Oreo", price: 25000)
Product.create!(category_id: 2, code: "SCND", name: "Matcha", price: 25000)
Product.create!(category_id: 2, code: "SCND", name: "Cf Đá Xay", price: 25000)
Product.create!(category_id: 2, code: "SCND", name: "Cf Nguyên Chất", price: 25000)
Product.create!(category_id: 2, code: "SCND", name: "Cf Nguyên Chất", price: 25000)
Product.create!(category_id: 2, code: "SCND", name: "Hạt dẻ (Hazelnut)", price: 25000)
Product.create!(category_id: 2, code: "SCND", name: "Hạt dẻ (Hazelnut)", price: 25000)
Product.create!(category_id: 2, code: "SCND", name: "Bạc Xỉu", price: 14000)
Product.create!(category_id: 2, code: "SCND", name: "Sữa Đá Đập", price: 15000)

Product.create!(category_id: 3, code: "TN", name: "Thuốc Ngựa", price: 1500)
Product.create!(category_id: 3, code: "TN", name: "Thuốc Ngựa Gói", price: 24000)
Product.create!(category_id: 3, code: "TS", name: "Thuốc Zed", price: 1500)
Product.create!(category_id: 3, code: "TS", name: "Thuốc Zed Gói", price: 24000)
Product.create!(category_id: 3, code: "TS", name: "Thuốc DunHill", price: 2000)
Product.create!(category_id: 3, code: "TS", name: "Thuốc DunHill Gói", price: 40000)
Product.create!(category_id: 3, code: "TS", name: "Ba Số", price: 2000)
Product.create!(category_id: 3, code: "TS", name: "Ba Số Gói", price: 40000)


Product.create!(category_id: 2, code: "SCND", name: "Soda Thơm", price: 25000)
Product.create!(category_id: 2, code: "SCND", name: "Soda Dâu Tây", price: 25000)
Product.create!(category_id: 2, code: "SCND", name: "Soda Xoài", price: 25000)
Product.create!(category_id: 2, code: "SCND", name: "Soda Việt Quất", price: 25000)
Product.create!(category_id: 2, code: "SCND", name: "Soda Chanh Dây", price: 25000)
Product.create!(category_id: 2, code: "SCND", name: "Mojito Thơm", price: 25000)
Product.create!(category_id: 2, code: "SCND", name: "Mojito Dâu Tây", price: 25000)
Product.create!(category_id: 2, code: "SCND", name: "Mojito Xoài", price: 25000)
Product.create!(category_id: 2, code: "SCND", name: "Mojito Việt Quất", price: 25000)
Product.create!(category_id: 2, code: "SCND", name: "Mojito Chanh Dây", price: 25000)


Product.create!(category_id: 2, code: "SCND", name: "S.Chua Dâu Tây", price: 25000)
Product.create!(category_id: 2, code: "SCND", name: "S.Chua Việt Quất", price: 25000)
Product.create!(category_id: 2, code: "SCND", name: "S.Chua Mâm Sôi", price: 25000)
Product.create!(category_id: 2, code: "SCND", name: "S.Chua Chanh Dây", price: 25000)
Product.create!(category_id: 2, code: "SCND", name: "S.Chua Xoài", price: 25000)
Product.create!(category_id: 2, code: "SCND", name: "S.Chua Đá Đập", price: 12000)

Product.create!(category_id: 2, code: "SCND", name: "Kem Bạc Hà", price: 25000)
Product.create!(category_id: 2, code: "SCND", name: "Kem Trà Xanh", price: 25000)
Product.create!(category_id: 2, code: "SCND", name: "Kem Sầu Riêng", price: 25000)
Product.create!(category_id: 2, code: "SCND", name: "Sữa Đá Nóng", price: 12000)
Product.create!(category_id: 2, code: "SCND", name: "Sữa Đá Đập", price: 12000)
